services:
  - type: web
    name: vitegourmand
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Vite & Gourmand"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_SECRET
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: vitegourmand_nosql
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: noreply@vitegourmand.fr
      - key: MAIL_FROM_NAME
        value: "Vite & Gourmand"
      - key: CONTACT_TO
        value: contact@vitegourmand.fr
